// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebAppRentAcar.Data;

#nullable disable

namespace WebAppRentAcar.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260329183533_CreateSeedDataForCars")]
    partial class CreateSeedDataForCars
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "c3c0e566-7368-4cad-b44e-b2204ec50164",
                            ConcurrencyStamp = "c3c0e566-7368-4cad-b44e-b2204ec50164",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "4e0462e4-6314-4f40-a4e4-6c3b05e4d915",
                            ConcurrencyStamp = "4e0462e4-6314-4f40-a4e4-6c3b05e4d915",
                            Name = "User",
                            NormalizedName = "USER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("WebAppRentAcar.Data.AppUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EGN")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("EGN")
                        .IsUnique();

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("WebAppRentAcar.Models.Car", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .HasMaxLength(4048)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Passengers")
                        .HasColumnType("int");

                    b.Property<decimal>("PricePerDay")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Cars");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Brand = "BMW",
                            Description = "Diesel, automatic, navigation",
                            Model = "320d",
                            Passengers = 5,
                            PricePerDay = 120m,
                            Year = 2018
                        },
                        new
                        {
                            Id = 2,
                            Brand = "Audi",
                            Description = "Petrol, automatic, leather seats",
                            Model = "A4",
                            Passengers = 5,
                            PricePerDay = 130m,
                            Year = 2019
                        },
                        new
                        {
                            Id = 3,
                            Brand = "Mercedes",
                            Description = "Diesel, automatic, premium interior",
                            Model = "C220",
                            Passengers = 5,
                            PricePerDay = 150m,
                            Year = 2020
                        },
                        new
                        {
                            Id = 4,
                            Brand = "VW",
                            Description = "Petrol, manual, economical",
                            Model = "Golf 7",
                            Passengers = 5,
                            PricePerDay = 80m,
                            Year = 2017
                        },
                        new
                        {
                            Id = 5,
                            Brand = "Toyota",
                            Description = "Hybrid, automatic, low consumption",
                            Model = "Corolla",
                            Passengers = 5,
                            PricePerDay = 110m,
                            Year = 2021
                        },
                        new
                        {
                            Id = 6,
                            Brand = "Ford",
                            Description = "Diesel, manual, comfortable",
                            Model = "Focus",
                            Passengers = 5,
                            PricePerDay = 90m,
                            Year = 2018
                        },
                        new
                        {
                            Id = 7,
                            Brand = "Honda",
                            Description = "Petrol, automatic, sporty",
                            Model = "Civic",
                            Passengers = 5,
                            PricePerDay = 115m,
                            Year = 2019
                        },
                        new
                        {
                            Id = 8,
                            Brand = "Hyundai",
                            Description = "Petrol, manual, reliable",
                            Model = "i30",
                            Passengers = 5,
                            PricePerDay = 85m,
                            Year = 2020
                        },
                        new
                        {
                            Id = 9,
                            Brand = "Kia",
                            Description = "Petrol, automatic, modern",
                            Model = "Ceed",
                            Passengers = 5,
                            PricePerDay = 95m,
                            Year = 2021
                        },
                        new
                        {
                            Id = 10,
                            Brand = "Skoda",
                            Description = "Diesel, automatic, spacious",
                            Model = "Octavia",
                            Passengers = 5,
                            PricePerDay = 105m,
                            Year = 2019
                        },
                        new
                        {
                            Id = 11,
                            Brand = "Nissan",
                            Description = "SUV, petrol, automatic",
                            Model = "Qashqai",
                            Passengers = 5,
                            PricePerDay = 140m,
                            Year = 2020
                        },
                        new
                        {
                            Id = 12,
                            Brand = "Mazda",
                            Description = "SUV, petrol, premium feel",
                            Model = "CX-5",
                            Passengers = 5,
                            PricePerDay = 145m,
                            Year = 2021
                        },
                        new
                        {
                            Id = 13,
                            Brand = "Peugeot",
                            Description = "SUV, diesel, stylish",
                            Model = "3008",
                            Passengers = 5,
                            PricePerDay = 135m,
                            Year = 2018
                        },
                        new
                        {
                            Id = 14,
                            Brand = "Renault",
                            Description = "Diesel, manual, budget",
                            Model = "Megane",
                            Passengers = 5,
                            PricePerDay = 75m,
                            Year = 2017
                        },
                        new
                        {
                            Id = 15,
                            Brand = "Opel",
                            Description = "Petrol, manual, practical",
                            Model = "Astra",
                            Passengers = 5,
                            PricePerDay = 80m,
                            Year = 2018
                        },
                        new
                        {
                            Id = 16,
                            Brand = "Tesla",
                            Description = "Electric, autopilot, premium",
                            Model = "Model 3",
                            Passengers = 5,
                            PricePerDay = 200m,
                            Year = 2022
                        },
                        new
                        {
                            Id = 17,
                            Brand = "Volvo",
                            Description = "SUV, hybrid, safety features",
                            Model = "XC60",
                            Passengers = 5,
                            PricePerDay = 180m,
                            Year = 2021
                        },
                        new
                        {
                            Id = 18,
                            Brand = "Jeep",
                            Description = "SUV, 4x4, off-road capable",
                            Model = "Compass",
                            Passengers = 5,
                            PricePerDay = 150m,
                            Year = 2020
                        },
                        new
                        {
                            Id = 19,
                            Brand = "Dacia",
                            Description = "SUV, budget, reliable",
                            Model = "Duster",
                            Passengers = 5,
                            PricePerDay = 70m,
                            Year = 2019
                        },
                        new
                        {
                            Id = 20,
                            Brand = "Seat",
                            Description = "Petrol, sporty, modern",
                            Model = "Leon",
                            Passengers = 5,
                            PricePerDay = 100m,
                            Year = 2021
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("WebAppRentAcar.Data.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("WebAppRentAcar.Data.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebAppRentAcar.Data.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("WebAppRentAcar.Data.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
